# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49224c6ecc014d9c2a9b22765af0860d06496b9d11c11714d4a7bbe08542b6b0318988ab1ef82470d58b10474def62293703a1537610d412a3ec91ccf24a55e6

test:
  secret_key_base: e628c025025dffed6dcac564bdbb76baec36c5d27ce8f5b46361a83b0cfab2fe15f579295a8c08be74b8abb71cd8512b15124464f013b89ba75b0332393b10db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
